import createLogger, { FatalError } from '@big-sister/logging'

const log = createLogger('core')
export default log

process.on('uncaughtException', handleUncaughtException)
process.on('unhandledRejection', handleUncaughtException)

function handleUncaughtException(err: any): void {
  if (err instanceof FatalError) {
    log.error(`A fatal error occured`)
  } else {
    log.error(`Uncaught exception: ${err.stack || err}`)
  }
  process.exit(1)
}
